dofile("data/scripts/lib/mod_settings.lua")

local lastMode = ModSettingGet("fungal-twitch.VOTE_MODE")
local valid_materials = {
	{"acid","acid"},
	{"acid_gas","flammable gas"},
	{"acid_gas_static","flammable gas"},
	{"alcohol","whiskey"},
	{"alcohol_gas","Whiskey fumes"},
	{"aluminium_molten","molten aluminium"},
	{"aluminium_oxide_molten","molten aluminium"},
	{"aluminium_robot_molten","molten aluminium"},
	{"blood","blood"},
	{"blood_cold","freezing liquid"},
	{"blood_cold_vapour","freezing vapour"},
	{"blood_fading","blood"},
	{"blood_fading_slow","blood"},
	{"blood_fungi","fungus blood"},
	{"blood_thick","blood"},
	{"blood_worm","worm blood"},
	{"bluefungi_static","blue fungus"},
	{"bone","bone dust"},
	{"bone_static","bone wall"},
	{"brass","brass"},
	{"brass_molten","molten brass"},
	{"burning_powder","burning powder"},
	{"bush_seed","evergreen seed"},
	{"ceiling_plant_material","seed"},
	{"cement","cement"},
	{"cheese_static","cheese"},
	{"cloud","cloud"},
	{"cloud_blood","blood mist"},
	{"cloud_lighter","cloud"},
	{"cloud_radioactive","toxic mist"},
	{"cloud_slime","slime mist"},
	{"coal","coal"},
	{"coal_static","coal vein"},
	{"concrete_sand","concrete"},
	{"concrete_static","concrete"},
	{"copper","copper"},
	{"copper_molten","molten copper"},
	{"corruption_static","corrupted rock"},
	{"creepy_liquid","creepy liquid"},
	{"creepy_liquid_emitter","brick wall"},
	{"cursed_liquid","Greed-cursed liquid"},
	{"diamond","diamond"},
	{"endslime","hell slime"},
	{"endslime_blood","hell slime"},
	{"endslime_static","hell slime"},
	{"explosion_dirt","dirt"},
	{"fire","fire"},
	{"fire_blue","fire"},
	{"flame","fire"},
	{"fungal_gas","fungal gas"},
	{"fungal_shift_particle_fx","fungal_shift_particle_fx"},
	{"fungi","weird fungus"},
	{"fungi_creeping","Mystery fungus"},
	{"fungi_creeping_secret","fungus"},
	{"fungi_green","fungus"},
	{"fungisoil","fungal soil"},
	{"fungus_powder","fungal soil"},
	{"fungus_powder_bad","fungal soil"},
	{"glass","glass"},
	{"glass_brittle","brittle glass"},
	{"glass_broken","glass"},
	{"glass_broken_molten","molten glass"},
	{"glass_molten","molten glass"},
	{"glass_static","glass"},
	{"glowshroom","glowing fungal spore"},
	{"glowstone","glowing stone"},
	{"glowstone_altar","glowing stone"},
	{"glowstone_altar_hdr","glowing stone"},
	{"glowstone_potion","glowing stone"},
	{"glue","Glue"},
	{"gold","gold"},
	{"gold_molten","molten gold"},
	{"gold_radioactive","toxic gold"},
	{"gold_static","gold vein"},
	{"gold_static_dark","vibrant gold vein"},
	{"gold_static_radioactive","toxic gold"},
	{"grass","grass"},
	{"grass_dark","grass"},
	{"grass_dry","grass"},
	{"grass_ice","ice"},
	{"gunpowder","gunpowder"},
	{"gunpowder_explosive","gunpowder"},
	{"gunpowder_tnt","gunpowder"},
	{"gunpowder_unstable","gunpowder"},
	{"gunpowder_unstable_big","gunpowder"},
	{"gunpowder_unstable_boss_limbs","slimy meat"},
	{"honey","honey"},
	{"ice","ice"},
	{"ice_acid_glass","frozen acid"},
	{"ice_acid_static","frozen acid"},
	{"ice_blood_glass","Frozen blood"},
	{"ice_blood_static","frozen blood"},
	{"ice_cold_glass","ice"},
	{"ice_cold_static","ice"},
	{"ice_glass_b2","ice"},
	{"ice_meteor_static","ice"},
	{"ice_poison_glass","Frozen poison"},
	{"ice_poison_static","Frozen poison"},
	{"ice_radioactive_glass","toxic ice"},
	{"ice_radioactive_static","toxic ice"},
	{"ice_slime_glass","Frozen slime"},
	{"ice_slime_static","Frozen slime"},
	{"ice_static","ice"},
	{"juhannussima","Juhannussima"},
	{"lava","lava"},
	{"lavarock_static","volcanic rock"},
	{"lavasand","volcanic sand"},
	{"liquid_fire","fire"},
	{"liquid_fire_weak","liquid fire"},
	{"magic_gas_hp_regeneration","Healium"},
	{"magic_liquid","gate-opener"},
	{"magic_liquid_berserk","berserkium"},
	{"magic_liquid_charm","pheromone"},
	{"magic_liquid_faster_levitation","levitatium"},
	{"magic_liquid_faster_levitation_and_movement","hastium"},
	{"magic_liquid_hp_regeneration","healthium"},
	{"magic_liquid_hp_regeneration_unstable","lively concoction"},
	{"magic_liquid_invisibility","invisiblium"},
	{"magic_liquid_mana_regeneration","concentrated mana"},
	{"magic_liquid_movement_faster","acceleratium"},
	{"magic_liquid_polymorph","polymorphine"},
	{"magic_liquid_protection_all","ambrosia"},
	{"magic_liquid_random_polymorph","chaotic polymorphine"},
	{"magic_liquid_teleportation","teleportatium"},
	{"magic_liquid_unstable_polymorph","unstable polymorphine"},
	{"magic_liquid_unstable_teleportation","unstable teleportatium"},
	{"magic_liquid_worm_attractor","worm pheromone"},
	{"material_confusion","flummoxium"},
	{"material_darkness","Ominous liquid"},
	{"material_rainbow","Rainbow"},
	{"meat_slime_sand","slimy meat"},
	{"metal_molten","molten metal"},
	{"metal_nohit_molten","molten metal"},
	{"metal_prop_molten","molten metal"},
	{"metal_rust_molten","molten metal"},
	{"metal_sand","Metal dust"},
	{"metal_sand_molten","Molten metal"},
	{"meteorite_static","meteorite"},
	{"midas","draught of midas"},
	{"midas_precursor","alchemic precursor"},
	{"monster_powder_test","Monstrous powder"},
	{"moss","moss"},
	{"moss_rust","rusty moss"},
	{"mud","mud"},
	{"mushroom","fungal spore"},
	{"mushroom_giant_blue","fungal spore"},
	{"mushroom_giant_red","fungal spore"},
	{"mushroom_seed","fungal spore"},
	{"nest_static","nest"},
	{"oil","oil"},
	{"orb_powder","Guiding powder"},
	{"pea_soup","pea soup"},
	{"peat","Peat"},
	{"plant_material","plant material"},
	{"plant_material_red","seed"},
	{"plant_seed","plant seed"},
	{"plasma_fading","magical liquid"},
	{"plasma_fading_bright","magical liquid"},
	{"plasma_fading_green","magical liquid"},
	{"plasma_fading_pink","magical liquid"},
	{"plastic_molten","molten plastic"},
	{"plastic_prop_molten","molten plastic"},
	{"plastic_red","plastic"},
	{"plastic_red_molten","molten plastic"},
	{"poison","Poison"},
	{"poison_gas","poison gas"},
	{"poo","excrement"},
	{"poo_gas","Nauseating gas"},
	{"porridge","Hearty Porridge"},
	{"purifying_powder","Purifying powder"},
	{"radioactive_gas","toxic gas"},
	{"radioactive_gas_static","toxic gas"},
	{"radioactive_liquid","toxic sludge"},
	{"radioactive_liquid_fading","toxic sludge"},
	{"radioactive_liquid_yellow","toxic sludge"},
	{"rainbow_gas","Unicorn farts"},
	{"rat_powder","Ratty powder"},
	{"rock_eroding","eroding rock"},
	{"rock_hard","dense rock"},
	{"rock_hard_border","extremely dense rock"},
	{"rock_magic_bottom","magic wall"},
	{"rock_magic_gate","magic gate"},
	{"rock_static","rock"},
	{"rock_static_cursed","Cursed rock"},
	{"rock_static_cursed_green","Greed-cursed rock"},
	{"rock_static_fungal","fungal soil"},
	{"rock_static_glow","glowing matter"},
	{"rock_static_grey","grey rock"},
	{"rock_static_intro","rock"},
	{"rock_static_intro_breakable","rock"},
	{"rock_static_noedge","rock"},
	{"rock_static_poison","poisonous rock"},
	{"rock_static_purple","rock"},
	{"rock_static_radioactive","toxic rock"},
	{"rock_static_trip_secret","rock"},
	{"rock_static_trip_secret2","rock"},
	{"rock_static_wet","damp rock"},
	{"rock_vault","vault rock"},
	{"rocket_particles","smoke"},
	{"root","vine"},
	{"root_growth","vine"},
	{"rotten_meat","rotten meat"},
	{"rotten_meat_radioactive","toxic meat"},
	{"rust_static","rusted metal"},
	{"salt","salt"},
	{"sand","sand"},
	{"sand_blue","blue sand"},
	{"sand_herb","herb"},
	{"sand_herb_vapour","funky vapour"},
	{"sand_petrify","sand"},
	{"sand_static","ground"},
	{"sand_static_bright","granite ground"},
	{"sand_static_rainforest","lush ground"},
	{"sand_static_rainforest_dark","lush ground"},
	{"sand_static_red","rusty ground"},
	{"sand_surface","sand"},
	{"sandstone","sandstone"},
	{"sandstone_surface","sandstone"},
	{"shock_powder","fungal soil"},
	{"silver","silver"},
	{"silver_molten","molten silver"},
	{"sima","Sima"},
	{"skullrock","hell rock"},
	{"slime","slime"},
	{"slime_green","slime"},
	{"slime_static","slime"},
	{"slime_yellow","slime"},
	{"slush","Slush"},
	{"smoke","smoke"},
	{"smoke_explosion","smoke"},
	{"smoke_magic","smoke"},
	{"smoke_static","smoke"},
	{"snow","snow"},
	{"snow_static","packed snow"},
	{"snow_sticky","snow"},
	{"snowrock_static","frozen rock"},
	{"sodium","sodium"},
	{"sodium_unstable","wet sodium"},
	{"soil","soil"},
	{"soil_dark","barren soil"},
	{"soil_dead","barren soil"},
	{"soil_lush","soil"},
	{"soil_lush_dark","soil"},
	{"spark","spark"},
	{"spark_blue","spark"},
	{"spark_blue_dark","spark"},
	{"spark_electric","electric spark"},
	{"spark_green","spark"},
	{"spark_green_bright","spark"},
	{"spark_player","spark"},
	{"spark_purple","spark"},
	{"spark_purple_bright","spark"},
	{"spark_red","spark"},
	{"spark_red_bright","spark"},
	{"spark_teal","spark"},
	{"spark_white","spark"},
	{"spark_white_bright","spark"},
	{"spark_yellow","spark"},
	{"spore","seed"},
	{"spore_pod_stalk","blue fungus"},
	{"steam","steam"},
	{"steam_trailer","steam"},
	{"steel_grey_static","dense steel"},
	{"steel_molten","molten metal"},
	{"steel_rust_molten","molten steel"},
	{"steel_rusted_no_holes","rusted steel"},
	{"steel_sand","steel"},
	{"steel_static","steel"},
	{"steel_static_molten","molten steel"},
	{"steel_static_strong","dense steel"},
	{"steel_static_unmeltable","hardened steel"},
	{"steelfrost_static","Frozen steel"},
	{"steelmoss_slanted","mossy steel"},
	{"steelmoss_slanted_molten","molten steel"},
	{"steelmoss_static","rusted steel"},
	{"steelmoss_static_molten","molten steel"},
	{"steelpipe_static","metal pipe"},
	{"steelsmoke_static","smoking steel"},
	{"steelsmoke_static_molten","molten steel"},
	{"sulphur","sulphur"},
	{"swamp","swamp"},
	{"templebrick_diamond_static","Diamond brickwork"},
	{"templebrick_golden_static","Fool's gold"},
	{"templebrick_moss_static","mossy brickwork"},
	{"templebrick_noedge_static","brickwork"},
	{"templebrick_red","brickwork"},
	{"templebrick_static","brickwork"},
	{"templebrick_static_broken","brickwork"},
	{"templebrick_static_ruined","Ruined brick wall"},
	{"templebrick_static_soft","brickwork"},
	{"templebrick_thick_static","brickwork"},
	{"templebrick_thick_static_noedge","brickwork"},
	{"templebrickdark_static","brickwork"},
	{"templerock_soft","brickwork"},
	{"templerock_static","brickwork"},
	{"templeslab_crumbling_static","brickwork"},
	{"templeslab_static","brickwork"},
	{"the_end","hell rock"},
	{"trailer_text","text"},
	{"tubematerial","neon tube"},
	{"urine","urine"},
	{"vine","vine"},
	{"void_liquid","Void liquid"},
	{"vomit","Vomit"},
	{"water","Water"},
	{"water_fading","Water"},
	{"water_ice","chilly water"},
	{"water_salt","brine"},
	{"water_static","Water"},
	{"water_swamp","swamp"},
	{"water_temp","Water"},
	{"waterrock","rock"},
	{"wax","wax"},
	{"wax_molten","molten wax"},
	{"wizardstone","Odd brickwork"},
	{"wood_burns_forever","wood"},
	{"wood_player","wood"},
	{"wood_static","wood"},
	{"wood_static_gas","pressurized wood"},
	{"wood_static_vertical","wood"},
	{"wood_static_wet","damp wood"},
	{"wood_tree","wood"},
}


function isMode(mode)
	if (lastMode == nil) then
		return mode == "anarchy"
	end
	return lastMode == mode
end

function mod_setting_bool_custom( mod_id, gui, in_main_menu, im_id, setting )
	local value = ModSettingGetNextValue( mod_setting_get_id(mod_id,setting) )
	local text = setting.ui_name .. " - " .. GameTextGet( value and "$option_on" or "$option_off" )

	if GuiButton( gui, im_id, mod_setting_group_x_offset, 0, text ) then
		ModSettingSetNextValue( mod_setting_get_id(mod_id,setting), not value, false )
	end

	mod_setting_tooltip( mod_id, gui, in_main_menu, setting )
end

function reset_rewards( mod_id, gui, in_main_menu, setting, old_value, new_value  )
	ModSettingSet("fungal-twitch.REWARD_FROM_ID", "")
	ModSettingSet("fungal-twitch.REWARD_TO_ID", "")
end

function mod_setting_change_callback( mod_id, gui, in_main_menu, setting, old_value, new_value  )
	if (setting ~= nil and setting.id == "VOTE_MODE") then
		lastMode = new_value
	end
end

local mod_id = "fungal-twitch"
mod_settings_version = 1

function getModSettings()
	local valid_settings = {}
	for _,material in ipairs(valid_materials) do
		table.insert(valid_settings, {
			id = material[1],
			ui_name = material[1],
			ui_description = material[2],
			value_default = true,
			scope = MOD_SETTING_SCOPE_NEW_GAME
		})
	end

	local mod_settings = {
		{
			id = "RESET_REWARD_IDS",
			ui_name = "Reset the twitch reward IDs",
			ui_description = "Only use this when\n- You made an error in the setup\n- You deleted and created new rewards\nChange the value to On/Off (doesn't matter) and start a new run",
			value_default = true,
			change_fn = reset_rewards,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			id = "SHOW_ILLEGAL_MATERIALS",
			ui_name = "Show recent illegal materials at the top of the screen",
			ui_description = "",
			value_default = true,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			id = "SHOW_COOLDOWNS",
			ui_name = "Show cooldowns at the top of the screen",
			ui_description = "",
			value_default = true,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			id = "LOG_SHIFT_RESULT_IN_GAME",
			ui_name = "Show a message when a shift happens",
			ui_description = "Toggle to show a message with the shift details when it happens or not.",
			value_default = true,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			id = "START_WITH_TELEPORT",
			ui_name = "Start with a small teleport bolt",
			ui_description = "",
			value_default = false,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			id = "START_WITH_FIRESTONE",
			ui_name = "Start with a firestone",
			ui_description = "",
			value_default = false,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			id = "START_WITH_PEACE",
			ui_name = "Start with the perk Peace with the gods",
			ui_description = "",
			value_default = false,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			id = "START_WITH_BREATHLESS",
			ui_name = "Start with the perk Breathless",
			ui_description = "",
			value_default = false,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
		},
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			id = "VOTE_MODE",
			ui_name = "Vote mode",
			ui_description = "Toggle me",
			value_default = "anarchy",
			values = { {"anarchy","[Anarchy]"}, {"democracy","[Democracy]"}, {"ti","[TI]"} },
			scope = MOD_SETTING_SCOPE_RUNTIME,
			change_fn = mod_setting_change_callback,
		},
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			id = "txt1",
			ui_name = "- Anarchy mode shifts as soon as the from and to materials are set",
			not_setting = true,
			hidden = not isMode("anarchy")
		},
		{
			id = "txt2",
			ui_name = "- Democracy mode collects votes and shifts at a set interval",
			not_setting = true,
			hidden = not isMode("democracy")
		},
		{
			id = "txt3",
			ui_name = "- TI mode uses random materials and lets chat vote like Twitch Integration",
			not_setting = true,
			hidden = not isMode("ti")
		},
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			id = "UNBALANCED_MODE",
			ui_name = "Unbalanced mode",
			ui_description = "Everyone can fully control a shift, both from and to",
			value_default = false,
			scope = MOD_SETTING_SCOPE_NEW_GAME,
			hidden = not isMode("anarchy")
		},
		{
      id = "ANARCHY_COOLDOWN",
      ui_name = "Anarchy cooldown per user",
      ui_description = "",
			value_default = 60,
			value_min = 0,
			value_max = 300,
			value_display_multiplier = 1,
			value_display_formatting = " $0 seconds",
			scope = MOD_SETTING_SCOPE_NEW_GAME,
			hidden = not isMode("anarchy")
    },
		{
      id = "DEMOCRACY_INTERVAL",
      ui_name = "Democracy interval",
      ui_description = "At what interval will shifts happen",
			value_default = 30,
			value_min = 10,
			value_max = 150,
			value_display_multiplier = 1,
			value_display_formatting = " $0 seconds",
			scope = MOD_SETTING_SCOPE_NEW_GAME,
			hidden = not isMode("democracy")
    },
		{
      id = "TI_INTERVAL",
      ui_name = "TI interval",
      ui_description = "At what interval will shifts happen",
			value_default = 45,
			value_min = 10,
			value_max = 150,
			value_display_multiplier = 1,
			value_display_formatting = " $0 seconds",
			scope = MOD_SETTING_SCOPE_NEW_GAME,
			hidden = not isMode("ti")
    },
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			ui_fn = mod_setting_vertical_spacing,
			not_setting = true,
		},
		{
			category_id = "VALID_MATERIALS",
			ui_name = "Valid materials",
			ui_description = "Turn a material off to ban it from being used in shifts",
			settings = valid_settings
		},
	}

	return mod_settings
end

function ModSettingsUpdate( init_scope )
	local old_version = mod_settings_get_version( mod_id )
	mod_settings_update( mod_id, getModSettings(), init_scope )
end

function ModSettingsGuiCount()
	return mod_settings_gui_count( mod_id, getModSettings() )
end

function ModSettingsGui( gui, in_main_menu )
	mod_settings_gui( mod_id, getModSettings(), gui, in_main_menu )
end
